defaults:
  - model: dino
  - dataset: imagenet100_lt
  - experiment: bridge
  - _self_

# General settings
seed: 42
name: ${experiment.name}_${model.name}_${dataset.name}
base_dir: ${oc.env:BASE_CACHE_DIR,/tmp}/bridge_experiments
use_wandb: True

# Training settings
trainer:
  max_epochs: 200
  precision: 32
  accelerator: gpu
  devices: auto
  strategy: ddp
  num_sanity_val_steps: 0

# Optimizer settings
optimizer:
  name: adamw
  lr: 0.0005
  weight_decay: 0.05
  batch_size: 256

# Data settings
data:
  num_workers: 4
  pin_memory: True
  image_size: 224
  
# Augmentation settings (for SSL)
augmentations:
  - rrc:
      crop_size: 224
      min_scale: 0.08
      max_scale: 1.0
  - color_jitter:
      brightness: 0.4
      contrast: 0.4
      saturation: 0.4
      hue: 0.1
  - random_gray_scale:
      prob: 0.2
  - random_horizontal_flip:
      prob: 0.5
  - normalize:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
