defaults:
  - model: dino
  - dataset: imagenet100_lt
  - experiment: bridge
  - _self_

# General settings
seed: 42
name: ${experiment.name}_${model.name}_${dataset.name}
base_dir: ${oc.env:BASE_CACHE_DIR,/tmp}/bridge_experiments
use_wandb: True

model:
  # Optimizer settings
  optimizer:
    lr: 0.0005
    weight_decay: 0.05
    batch_size: 256

# Data settings
dataset:
  num_workers: 4
  pin_memory: True
  image_size: 224
