bridge: ${hydra:compose:/bridge/bridge}

checkpoint:
  dir: /var/scratch/ssalehid/BRIDGE/checkpoints
  enabled: True
  frequency: 100
  keep_prev: True

wandb:
  enabled: True
  project: bridge
  entity: filipelaitenberger

precision: 32
devices: auto
accelerator: "gpu"
strategy: "ddp"
