name: imagenet100_lt

train_path: "flaitenberger/imagenet-100-LT"
val_path: "flaitenberger/imagenet-100-LT"
test_path: "flaitenberger/imagenet-100-LT"
removed_data_path: "flaitenberger/imagenet-100-LT-removed-data"
split:
  train: "train"
  val: "validation"
  test: "test"
num_classes: 100

